// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YFQAppService.proto

#ifndef PROTOBUF_YFQAppService_2eproto__INCLUDED
#define PROTOBUF_YFQAppService_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace YFQAppService {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_YFQAppService_2eproto();
void protobuf_AssignDesc_YFQAppService_2eproto();
void protobuf_ShutdownFile_YFQAppService_2eproto();

class LoginReq;
class LoginRes;
class HeartBeatReq;
class HeartBeatRes;
class LogoutReq;
class GpsReq;
class GpsRes;

enum MessageCmdID {
  CID_LOGIN_REQ_MSG = 257,
  CID_LOGIN_RES_MSG = 258,
  CID_HEARTBEAT_REQ_MSG = 259,
  CID_HEARTBEAT_RES_MSG = 260,
  CID_LOGINOUT_REQ_MSG = 261,
  CID_GPS_REQ_MSG = 262,
  CID_GPS_RES_MSG = 263
};
bool MessageCmdID_IsValid(int value);
const MessageCmdID MessageCmdID_MIN = CID_LOGIN_REQ_MSG;
const MessageCmdID MessageCmdID_MAX = CID_GPS_RES_MSG;
const int MessageCmdID_ARRAYSIZE = MessageCmdID_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageCmdID_descriptor();
inline const ::std::string& MessageCmdID_Name(MessageCmdID value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageCmdID_descriptor(), value);
}
inline bool MessageCmdID_Parse(
    const ::std::string& name, MessageCmdID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageCmdID>(
    MessageCmdID_descriptor(), name, value);
}
enum LoginResultType {
  LOGIN_RESULT_NONE = 0,
  LOGIN_RESULT_OK = 1,
  LOGIN_RESULT_FAILED = 2
};
bool LoginResultType_IsValid(int value);
const LoginResultType LoginResultType_MIN = LOGIN_RESULT_NONE;
const LoginResultType LoginResultType_MAX = LOGIN_RESULT_FAILED;
const int LoginResultType_ARRAYSIZE = LoginResultType_MAX + 1;

const ::google::protobuf::EnumDescriptor* LoginResultType_descriptor();
inline const ::std::string& LoginResultType_Name(LoginResultType value) {
  return ::google::protobuf::internal::NameOfEnum(
    LoginResultType_descriptor(), value);
}
inline bool LoginResultType_Parse(
    const ::std::string& name, LoginResultType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LoginResultType>(
    LoginResultType_descriptor(), name, value);
}
enum GpsResultType {
  GPS_RESULT_NONE = 0,
  GPS_RESULT_OK = 1,
  GPS_RESULT_FAILED = 2
};
bool GpsResultType_IsValid(int value);
const GpsResultType GpsResultType_MIN = GPS_RESULT_NONE;
const GpsResultType GpsResultType_MAX = GPS_RESULT_FAILED;
const int GpsResultType_ARRAYSIZE = GpsResultType_MAX + 1;

const ::google::protobuf::EnumDescriptor* GpsResultType_descriptor();
inline const ::std::string& GpsResultType_Name(GpsResultType value) {
  return ::google::protobuf::internal::NameOfEnum(
    GpsResultType_descriptor(), value);
}
inline bool GpsResultType_Parse(
    const ::std::string& name, GpsResultType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GpsResultType>(
    GpsResultType_descriptor(), name, value);
}
// ===================================================================

class LoginReq : public ::google::protobuf::Message {
 public:
  LoginReq();
  virtual ~LoginReq();

  LoginReq(const LoginReq& from);

  inline LoginReq& operator=(const LoginReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginReq& default_instance();

  void Swap(LoginReq* other);

  // implements Message ----------------------------------------------

  inline LoginReq* New() const { return New(NULL); }

  LoginReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginReq& from);
  void MergeFrom(const LoginReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LoginReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string user_name = 1;
  inline bool has_user_name() const;
  inline void clear_user_name();
  static const int kUserNameFieldNumber = 1;
  inline const ::std::string& user_name() const;
  inline void set_user_name(const ::std::string& value);
  inline void set_user_name(const char* value);
  inline void set_user_name(const char* value, size_t size);
  inline ::std::string* mutable_user_name();
  inline ::std::string* release_user_name();
  inline void set_allocated_user_name(::std::string* user_name);

  // required string password = 2;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 2;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // optional string reversed = 10;
  inline bool has_reversed() const;
  inline void clear_reversed();
  static const int kReversedFieldNumber = 10;
  inline const ::std::string& reversed() const;
  inline void set_reversed(const ::std::string& value);
  inline void set_reversed(const char* value);
  inline void set_reversed(const char* value, size_t size);
  inline ::std::string* mutable_reversed();
  inline ::std::string* release_reversed();
  inline void set_allocated_reversed(::std::string* reversed);

  // @@protoc_insertion_point(class_scope:YFQAppService.LoginReq)
 private:
  inline void set_has_user_name();
  inline void clear_has_user_name();
  inline void set_has_password();
  inline void clear_has_password();
  inline void set_has_reversed();
  inline void clear_has_reversed();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr user_name_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::internal::ArenaStringPtr reversed_;
  friend void  protobuf_AddDesc_YFQAppService_2eproto();
  friend void protobuf_AssignDesc_YFQAppService_2eproto();
  friend void protobuf_ShutdownFile_YFQAppService_2eproto();

  void InitAsDefaultInstance();
  static LoginReq* default_instance_;
};
// -------------------------------------------------------------------

class LoginRes : public ::google::protobuf::Message {
 public:
  LoginRes();
  virtual ~LoginRes();

  LoginRes(const LoginRes& from);

  inline LoginRes& operator=(const LoginRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRes& default_instance();

  void Swap(LoginRes* other);

  // implements Message ----------------------------------------------

  inline LoginRes* New() const { return New(NULL); }

  LoginRes* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginRes& from);
  void MergeFrom(const LoginRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LoginRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .YFQAppService.LoginResultType result_code = 1;
  inline bool has_result_code() const;
  inline void clear_result_code();
  static const int kResultCodeFieldNumber = 1;
  inline ::YFQAppService::LoginResultType result_code() const;
  inline void set_result_code(::YFQAppService::LoginResultType value);

  // optional string result_string = 2;
  inline bool has_result_string() const;
  inline void clear_result_string();
  static const int kResultStringFieldNumber = 2;
  inline const ::std::string& result_string() const;
  inline void set_result_string(const ::std::string& value);
  inline void set_result_string(const char* value);
  inline void set_result_string(const char* value, size_t size);
  inline ::std::string* mutable_result_string();
  inline ::std::string* release_result_string();
  inline void set_allocated_result_string(::std::string* result_string);

  // optional string reversed = 10;
  inline bool has_reversed() const;
  inline void clear_reversed();
  static const int kReversedFieldNumber = 10;
  inline const ::std::string& reversed() const;
  inline void set_reversed(const ::std::string& value);
  inline void set_reversed(const char* value);
  inline void set_reversed(const char* value, size_t size);
  inline ::std::string* mutable_reversed();
  inline ::std::string* release_reversed();
  inline void set_allocated_reversed(::std::string* reversed);

  // @@protoc_insertion_point(class_scope:YFQAppService.LoginRes)
 private:
  inline void set_has_result_code();
  inline void clear_has_result_code();
  inline void set_has_result_string();
  inline void clear_has_result_string();
  inline void set_has_reversed();
  inline void clear_has_reversed();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr result_string_;
  ::google::protobuf::internal::ArenaStringPtr reversed_;
  int result_code_;
  friend void  protobuf_AddDesc_YFQAppService_2eproto();
  friend void protobuf_AssignDesc_YFQAppService_2eproto();
  friend void protobuf_ShutdownFile_YFQAppService_2eproto();

  void InitAsDefaultInstance();
  static LoginRes* default_instance_;
};
// -------------------------------------------------------------------

class HeartBeatReq : public ::google::protobuf::Message {
 public:
  HeartBeatReq();
  virtual ~HeartBeatReq();

  HeartBeatReq(const HeartBeatReq& from);

  inline HeartBeatReq& operator=(const HeartBeatReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartBeatReq& default_instance();

  void Swap(HeartBeatReq* other);

  // implements Message ----------------------------------------------

  inline HeartBeatReq* New() const { return New(NULL); }

  HeartBeatReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeartBeatReq& from);
  void MergeFrom(const HeartBeatReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HeartBeatReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string user_name = 1;
  inline bool has_user_name() const;
  inline void clear_user_name();
  static const int kUserNameFieldNumber = 1;
  inline const ::std::string& user_name() const;
  inline void set_user_name(const ::std::string& value);
  inline void set_user_name(const char* value);
  inline void set_user_name(const char* value, size_t size);
  inline ::std::string* mutable_user_name();
  inline ::std::string* release_user_name();
  inline void set_allocated_user_name(::std::string* user_name);

  // required uint32 msg_id = 2;
  inline bool has_msg_id() const;
  inline void clear_msg_id();
  static const int kMsgIdFieldNumber = 2;
  inline ::google::protobuf::uint32 msg_id() const;
  inline void set_msg_id(::google::protobuf::uint32 value);

  // optional string reversed = 10;
  inline bool has_reversed() const;
  inline void clear_reversed();
  static const int kReversedFieldNumber = 10;
  inline const ::std::string& reversed() const;
  inline void set_reversed(const ::std::string& value);
  inline void set_reversed(const char* value);
  inline void set_reversed(const char* value, size_t size);
  inline ::std::string* mutable_reversed();
  inline ::std::string* release_reversed();
  inline void set_allocated_reversed(::std::string* reversed);

  // @@protoc_insertion_point(class_scope:YFQAppService.HeartBeatReq)
 private:
  inline void set_has_user_name();
  inline void clear_has_user_name();
  inline void set_has_msg_id();
  inline void clear_has_msg_id();
  inline void set_has_reversed();
  inline void clear_has_reversed();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr user_name_;
  ::google::protobuf::internal::ArenaStringPtr reversed_;
  ::google::protobuf::uint32 msg_id_;
  friend void  protobuf_AddDesc_YFQAppService_2eproto();
  friend void protobuf_AssignDesc_YFQAppService_2eproto();
  friend void protobuf_ShutdownFile_YFQAppService_2eproto();

  void InitAsDefaultInstance();
  static HeartBeatReq* default_instance_;
};
// -------------------------------------------------------------------

class HeartBeatRes : public ::google::protobuf::Message {
 public:
  HeartBeatRes();
  virtual ~HeartBeatRes();

  HeartBeatRes(const HeartBeatRes& from);

  inline HeartBeatRes& operator=(const HeartBeatRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartBeatRes& default_instance();

  void Swap(HeartBeatRes* other);

  // implements Message ----------------------------------------------

  inline HeartBeatRes* New() const { return New(NULL); }

  HeartBeatRes* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeartBeatRes& from);
  void MergeFrom(const HeartBeatRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HeartBeatRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string user_name = 1;
  inline bool has_user_name() const;
  inline void clear_user_name();
  static const int kUserNameFieldNumber = 1;
  inline const ::std::string& user_name() const;
  inline void set_user_name(const ::std::string& value);
  inline void set_user_name(const char* value);
  inline void set_user_name(const char* value, size_t size);
  inline ::std::string* mutable_user_name();
  inline ::std::string* release_user_name();
  inline void set_allocated_user_name(::std::string* user_name);

  // required uint32 msg_id = 2;
  inline bool has_msg_id() const;
  inline void clear_msg_id();
  static const int kMsgIdFieldNumber = 2;
  inline ::google::protobuf::uint32 msg_id() const;
  inline void set_msg_id(::google::protobuf::uint32 value);

  // optional string reversed = 10;
  inline bool has_reversed() const;
  inline void clear_reversed();
  static const int kReversedFieldNumber = 10;
  inline const ::std::string& reversed() const;
  inline void set_reversed(const ::std::string& value);
  inline void set_reversed(const char* value);
  inline void set_reversed(const char* value, size_t size);
  inline ::std::string* mutable_reversed();
  inline ::std::string* release_reversed();
  inline void set_allocated_reversed(::std::string* reversed);

  // @@protoc_insertion_point(class_scope:YFQAppService.HeartBeatRes)
 private:
  inline void set_has_user_name();
  inline void clear_has_user_name();
  inline void set_has_msg_id();
  inline void clear_has_msg_id();
  inline void set_has_reversed();
  inline void clear_has_reversed();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr user_name_;
  ::google::protobuf::internal::ArenaStringPtr reversed_;
  ::google::protobuf::uint32 msg_id_;
  friend void  protobuf_AddDesc_YFQAppService_2eproto();
  friend void protobuf_AssignDesc_YFQAppService_2eproto();
  friend void protobuf_ShutdownFile_YFQAppService_2eproto();

  void InitAsDefaultInstance();
  static HeartBeatRes* default_instance_;
};
// -------------------------------------------------------------------

class LogoutReq : public ::google::protobuf::Message {
 public:
  LogoutReq();
  virtual ~LogoutReq();

  LogoutReq(const LogoutReq& from);

  inline LogoutReq& operator=(const LogoutReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogoutReq& default_instance();

  void Swap(LogoutReq* other);

  // implements Message ----------------------------------------------

  inline LogoutReq* New() const { return New(NULL); }

  LogoutReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogoutReq& from);
  void MergeFrom(const LogoutReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LogoutReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string user_name = 1;
  inline bool has_user_name() const;
  inline void clear_user_name();
  static const int kUserNameFieldNumber = 1;
  inline const ::std::string& user_name() const;
  inline void set_user_name(const ::std::string& value);
  inline void set_user_name(const char* value);
  inline void set_user_name(const char* value, size_t size);
  inline ::std::string* mutable_user_name();
  inline ::std::string* release_user_name();
  inline void set_allocated_user_name(::std::string* user_name);

  // optional string reversed = 10;
  inline bool has_reversed() const;
  inline void clear_reversed();
  static const int kReversedFieldNumber = 10;
  inline const ::std::string& reversed() const;
  inline void set_reversed(const ::std::string& value);
  inline void set_reversed(const char* value);
  inline void set_reversed(const char* value, size_t size);
  inline ::std::string* mutable_reversed();
  inline ::std::string* release_reversed();
  inline void set_allocated_reversed(::std::string* reversed);

  // @@protoc_insertion_point(class_scope:YFQAppService.LogoutReq)
 private:
  inline void set_has_user_name();
  inline void clear_has_user_name();
  inline void set_has_reversed();
  inline void clear_has_reversed();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr user_name_;
  ::google::protobuf::internal::ArenaStringPtr reversed_;
  friend void  protobuf_AddDesc_YFQAppService_2eproto();
  friend void protobuf_AssignDesc_YFQAppService_2eproto();
  friend void protobuf_ShutdownFile_YFQAppService_2eproto();

  void InitAsDefaultInstance();
  static LogoutReq* default_instance_;
};
// -------------------------------------------------------------------

class GpsReq : public ::google::protobuf::Message {
 public:
  GpsReq();
  virtual ~GpsReq();

  GpsReq(const GpsReq& from);

  inline GpsReq& operator=(const GpsReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GpsReq& default_instance();

  void Swap(GpsReq* other);

  // implements Message ----------------------------------------------

  inline GpsReq* New() const { return New(NULL); }

  GpsReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GpsReq& from);
  void MergeFrom(const GpsReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GpsReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string user_name = 1;
  inline bool has_user_name() const;
  inline void clear_user_name();
  static const int kUserNameFieldNumber = 1;
  inline const ::std::string& user_name() const;
  inline void set_user_name(const ::std::string& value);
  inline void set_user_name(const char* value);
  inline void set_user_name(const char* value, size_t size);
  inline ::std::string* mutable_user_name();
  inline ::std::string* release_user_name();
  inline void set_allocated_user_name(::std::string* user_name);

  // required double longitude = 2;
  inline bool has_longitude() const;
  inline void clear_longitude();
  static const int kLongitudeFieldNumber = 2;
  inline double longitude() const;
  inline void set_longitude(double value);

  // required double latitude = 3;
  inline bool has_latitude() const;
  inline void clear_latitude();
  static const int kLatitudeFieldNumber = 3;
  inline double latitude() const;
  inline void set_latitude(double value);

  // optional string address = 4;
  inline bool has_address() const;
  inline void clear_address();
  static const int kAddressFieldNumber = 4;
  inline const ::std::string& address() const;
  inline void set_address(const ::std::string& value);
  inline void set_address(const char* value);
  inline void set_address(const char* value, size_t size);
  inline ::std::string* mutable_address();
  inline ::std::string* release_address();
  inline void set_allocated_address(::std::string* address);

  // optional string date_time = 5;
  inline bool has_date_time() const;
  inline void clear_date_time();
  static const int kDateTimeFieldNumber = 5;
  inline const ::std::string& date_time() const;
  inline void set_date_time(const ::std::string& value);
  inline void set_date_time(const char* value);
  inline void set_date_time(const char* value, size_t size);
  inline ::std::string* mutable_date_time();
  inline ::std::string* release_date_time();
  inline void set_allocated_date_time(::std::string* date_time);

  // optional string user_id = 6;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 6;
  inline const ::std::string& user_id() const;
  inline void set_user_id(const ::std::string& value);
  inline void set_user_id(const char* value);
  inline void set_user_id(const char* value, size_t size);
  inline ::std::string* mutable_user_id();
  inline ::std::string* release_user_id();
  inline void set_allocated_user_id(::std::string* user_id);

  // optional string reversed = 10;
  inline bool has_reversed() const;
  inline void clear_reversed();
  static const int kReversedFieldNumber = 10;
  inline const ::std::string& reversed() const;
  inline void set_reversed(const ::std::string& value);
  inline void set_reversed(const char* value);
  inline void set_reversed(const char* value, size_t size);
  inline ::std::string* mutable_reversed();
  inline ::std::string* release_reversed();
  inline void set_allocated_reversed(::std::string* reversed);

  // @@protoc_insertion_point(class_scope:YFQAppService.GpsReq)
 private:
  inline void set_has_user_name();
  inline void clear_has_user_name();
  inline void set_has_longitude();
  inline void clear_has_longitude();
  inline void set_has_latitude();
  inline void clear_has_latitude();
  inline void set_has_address();
  inline void clear_has_address();
  inline void set_has_date_time();
  inline void clear_has_date_time();
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_reversed();
  inline void clear_has_reversed();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr user_name_;
  double longitude_;
  double latitude_;
  ::google::protobuf::internal::ArenaStringPtr address_;
  ::google::protobuf::internal::ArenaStringPtr date_time_;
  ::google::protobuf::internal::ArenaStringPtr user_id_;
  ::google::protobuf::internal::ArenaStringPtr reversed_;
  friend void  protobuf_AddDesc_YFQAppService_2eproto();
  friend void protobuf_AssignDesc_YFQAppService_2eproto();
  friend void protobuf_ShutdownFile_YFQAppService_2eproto();

  void InitAsDefaultInstance();
  static GpsReq* default_instance_;
};
// -------------------------------------------------------------------

class GpsRes : public ::google::protobuf::Message {
 public:
  GpsRes();
  virtual ~GpsRes();

  GpsRes(const GpsRes& from);

  inline GpsRes& operator=(const GpsRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GpsRes& default_instance();

  void Swap(GpsRes* other);

  // implements Message ----------------------------------------------

  inline GpsRes* New() const { return New(NULL); }

  GpsRes* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GpsRes& from);
  void MergeFrom(const GpsRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GpsRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .YFQAppService.GpsResultType result_code = 1;
  inline bool has_result_code() const;
  inline void clear_result_code();
  static const int kResultCodeFieldNumber = 1;
  inline ::YFQAppService::GpsResultType result_code() const;
  inline void set_result_code(::YFQAppService::GpsResultType value);

  // optional string result_string = 2;
  inline bool has_result_string() const;
  inline void clear_result_string();
  static const int kResultStringFieldNumber = 2;
  inline const ::std::string& result_string() const;
  inline void set_result_string(const ::std::string& value);
  inline void set_result_string(const char* value);
  inline void set_result_string(const char* value, size_t size);
  inline ::std::string* mutable_result_string();
  inline ::std::string* release_result_string();
  inline void set_allocated_result_string(::std::string* result_string);

  // optional string reversed = 10;
  inline bool has_reversed() const;
  inline void clear_reversed();
  static const int kReversedFieldNumber = 10;
  inline const ::std::string& reversed() const;
  inline void set_reversed(const ::std::string& value);
  inline void set_reversed(const char* value);
  inline void set_reversed(const char* value, size_t size);
  inline ::std::string* mutable_reversed();
  inline ::std::string* release_reversed();
  inline void set_allocated_reversed(::std::string* reversed);

  // @@protoc_insertion_point(class_scope:YFQAppService.GpsRes)
 private:
  inline void set_has_result_code();
  inline void clear_has_result_code();
  inline void set_has_result_string();
  inline void clear_has_result_string();
  inline void set_has_reversed();
  inline void clear_has_reversed();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr result_string_;
  ::google::protobuf::internal::ArenaStringPtr reversed_;
  int result_code_;
  friend void  protobuf_AddDesc_YFQAppService_2eproto();
  friend void protobuf_AssignDesc_YFQAppService_2eproto();
  friend void protobuf_ShutdownFile_YFQAppService_2eproto();

  void InitAsDefaultInstance();
  static GpsRes* default_instance_;
};
// ===================================================================


// ===================================================================

// LoginReq

// required string user_name = 1;
inline bool LoginReq::has_user_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginReq::set_has_user_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginReq::clear_has_user_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginReq::clear_user_name() {
  user_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user_name();
}
inline const ::std::string& LoginReq::user_name() const {
  // @@protoc_insertion_point(field_get:YFQAppService.LoginReq.user_name)
  return user_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginReq::set_user_name(const ::std::string& value) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.LoginReq.user_name)
}
inline void LoginReq::set_user_name(const char* value) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.LoginReq.user_name)
}
inline void LoginReq::set_user_name(const char* value, size_t size) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.LoginReq.user_name)
}
inline ::std::string* LoginReq::mutable_user_name() {
  set_has_user_name();
  // @@protoc_insertion_point(field_mutable:YFQAppService.LoginReq.user_name)
  return user_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginReq::release_user_name() {
  clear_has_user_name();
  return user_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginReq::set_allocated_user_name(::std::string* user_name) {
  if (user_name != NULL) {
    set_has_user_name();
  } else {
    clear_has_user_name();
  }
  user_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_name);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.LoginReq.user_name)
}

// required string password = 2;
inline bool LoginReq::has_password() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginReq::set_has_password() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginReq::clear_has_password() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginReq::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_password();
}
inline const ::std::string& LoginReq::password() const {
  // @@protoc_insertion_point(field_get:YFQAppService.LoginReq.password)
  return password_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginReq::set_password(const ::std::string& value) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.LoginReq.password)
}
inline void LoginReq::set_password(const char* value) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.LoginReq.password)
}
inline void LoginReq::set_password(const char* value, size_t size) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.LoginReq.password)
}
inline ::std::string* LoginReq::mutable_password() {
  set_has_password();
  // @@protoc_insertion_point(field_mutable:YFQAppService.LoginReq.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginReq::release_password() {
  clear_has_password();
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginReq::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    set_has_password();
  } else {
    clear_has_password();
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.LoginReq.password)
}

// optional string reversed = 10;
inline bool LoginReq::has_reversed() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LoginReq::set_has_reversed() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LoginReq::clear_has_reversed() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LoginReq::clear_reversed() {
  reversed_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_reversed();
}
inline const ::std::string& LoginReq::reversed() const {
  // @@protoc_insertion_point(field_get:YFQAppService.LoginReq.reversed)
  return reversed_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginReq::set_reversed(const ::std::string& value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.LoginReq.reversed)
}
inline void LoginReq::set_reversed(const char* value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.LoginReq.reversed)
}
inline void LoginReq::set_reversed(const char* value, size_t size) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.LoginReq.reversed)
}
inline ::std::string* LoginReq::mutable_reversed() {
  set_has_reversed();
  // @@protoc_insertion_point(field_mutable:YFQAppService.LoginReq.reversed)
  return reversed_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginReq::release_reversed() {
  clear_has_reversed();
  return reversed_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginReq::set_allocated_reversed(::std::string* reversed) {
  if (reversed != NULL) {
    set_has_reversed();
  } else {
    clear_has_reversed();
  }
  reversed_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reversed);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.LoginReq.reversed)
}

// -------------------------------------------------------------------

// LoginRes

// required .YFQAppService.LoginResultType result_code = 1;
inline bool LoginRes::has_result_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginRes::set_has_result_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginRes::clear_has_result_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginRes::clear_result_code() {
  result_code_ = 0;
  clear_has_result_code();
}
inline ::YFQAppService::LoginResultType LoginRes::result_code() const {
  // @@protoc_insertion_point(field_get:YFQAppService.LoginRes.result_code)
  return static_cast< ::YFQAppService::LoginResultType >(result_code_);
}
inline void LoginRes::set_result_code(::YFQAppService::LoginResultType value) {
  assert(::YFQAppService::LoginResultType_IsValid(value));
  set_has_result_code();
  result_code_ = value;
  // @@protoc_insertion_point(field_set:YFQAppService.LoginRes.result_code)
}

// optional string result_string = 2;
inline bool LoginRes::has_result_string() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginRes::set_has_result_string() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginRes::clear_has_result_string() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginRes::clear_result_string() {
  result_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_result_string();
}
inline const ::std::string& LoginRes::result_string() const {
  // @@protoc_insertion_point(field_get:YFQAppService.LoginRes.result_string)
  return result_string_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRes::set_result_string(const ::std::string& value) {
  set_has_result_string();
  result_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.LoginRes.result_string)
}
inline void LoginRes::set_result_string(const char* value) {
  set_has_result_string();
  result_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.LoginRes.result_string)
}
inline void LoginRes::set_result_string(const char* value, size_t size) {
  set_has_result_string();
  result_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.LoginRes.result_string)
}
inline ::std::string* LoginRes::mutable_result_string() {
  set_has_result_string();
  // @@protoc_insertion_point(field_mutable:YFQAppService.LoginRes.result_string)
  return result_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginRes::release_result_string() {
  clear_has_result_string();
  return result_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRes::set_allocated_result_string(::std::string* result_string) {
  if (result_string != NULL) {
    set_has_result_string();
  } else {
    clear_has_result_string();
  }
  result_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), result_string);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.LoginRes.result_string)
}

// optional string reversed = 10;
inline bool LoginRes::has_reversed() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LoginRes::set_has_reversed() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LoginRes::clear_has_reversed() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LoginRes::clear_reversed() {
  reversed_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_reversed();
}
inline const ::std::string& LoginRes::reversed() const {
  // @@protoc_insertion_point(field_get:YFQAppService.LoginRes.reversed)
  return reversed_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRes::set_reversed(const ::std::string& value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.LoginRes.reversed)
}
inline void LoginRes::set_reversed(const char* value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.LoginRes.reversed)
}
inline void LoginRes::set_reversed(const char* value, size_t size) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.LoginRes.reversed)
}
inline ::std::string* LoginRes::mutable_reversed() {
  set_has_reversed();
  // @@protoc_insertion_point(field_mutable:YFQAppService.LoginRes.reversed)
  return reversed_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginRes::release_reversed() {
  clear_has_reversed();
  return reversed_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRes::set_allocated_reversed(::std::string* reversed) {
  if (reversed != NULL) {
    set_has_reversed();
  } else {
    clear_has_reversed();
  }
  reversed_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reversed);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.LoginRes.reversed)
}

// -------------------------------------------------------------------

// HeartBeatReq

// required string user_name = 1;
inline bool HeartBeatReq::has_user_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeartBeatReq::set_has_user_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeartBeatReq::clear_has_user_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeartBeatReq::clear_user_name() {
  user_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user_name();
}
inline const ::std::string& HeartBeatReq::user_name() const {
  // @@protoc_insertion_point(field_get:YFQAppService.HeartBeatReq.user_name)
  return user_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HeartBeatReq::set_user_name(const ::std::string& value) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.HeartBeatReq.user_name)
}
inline void HeartBeatReq::set_user_name(const char* value) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.HeartBeatReq.user_name)
}
inline void HeartBeatReq::set_user_name(const char* value, size_t size) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.HeartBeatReq.user_name)
}
inline ::std::string* HeartBeatReq::mutable_user_name() {
  set_has_user_name();
  // @@protoc_insertion_point(field_mutable:YFQAppService.HeartBeatReq.user_name)
  return user_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HeartBeatReq::release_user_name() {
  clear_has_user_name();
  return user_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HeartBeatReq::set_allocated_user_name(::std::string* user_name) {
  if (user_name != NULL) {
    set_has_user_name();
  } else {
    clear_has_user_name();
  }
  user_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_name);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.HeartBeatReq.user_name)
}

// required uint32 msg_id = 2;
inline bool HeartBeatReq::has_msg_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HeartBeatReq::set_has_msg_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HeartBeatReq::clear_has_msg_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HeartBeatReq::clear_msg_id() {
  msg_id_ = 0u;
  clear_has_msg_id();
}
inline ::google::protobuf::uint32 HeartBeatReq::msg_id() const {
  // @@protoc_insertion_point(field_get:YFQAppService.HeartBeatReq.msg_id)
  return msg_id_;
}
inline void HeartBeatReq::set_msg_id(::google::protobuf::uint32 value) {
  set_has_msg_id();
  msg_id_ = value;
  // @@protoc_insertion_point(field_set:YFQAppService.HeartBeatReq.msg_id)
}

// optional string reversed = 10;
inline bool HeartBeatReq::has_reversed() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HeartBeatReq::set_has_reversed() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HeartBeatReq::clear_has_reversed() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HeartBeatReq::clear_reversed() {
  reversed_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_reversed();
}
inline const ::std::string& HeartBeatReq::reversed() const {
  // @@protoc_insertion_point(field_get:YFQAppService.HeartBeatReq.reversed)
  return reversed_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HeartBeatReq::set_reversed(const ::std::string& value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.HeartBeatReq.reversed)
}
inline void HeartBeatReq::set_reversed(const char* value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.HeartBeatReq.reversed)
}
inline void HeartBeatReq::set_reversed(const char* value, size_t size) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.HeartBeatReq.reversed)
}
inline ::std::string* HeartBeatReq::mutable_reversed() {
  set_has_reversed();
  // @@protoc_insertion_point(field_mutable:YFQAppService.HeartBeatReq.reversed)
  return reversed_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HeartBeatReq::release_reversed() {
  clear_has_reversed();
  return reversed_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HeartBeatReq::set_allocated_reversed(::std::string* reversed) {
  if (reversed != NULL) {
    set_has_reversed();
  } else {
    clear_has_reversed();
  }
  reversed_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reversed);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.HeartBeatReq.reversed)
}

// -------------------------------------------------------------------

// HeartBeatRes

// required string user_name = 1;
inline bool HeartBeatRes::has_user_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeartBeatRes::set_has_user_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeartBeatRes::clear_has_user_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeartBeatRes::clear_user_name() {
  user_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user_name();
}
inline const ::std::string& HeartBeatRes::user_name() const {
  // @@protoc_insertion_point(field_get:YFQAppService.HeartBeatRes.user_name)
  return user_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HeartBeatRes::set_user_name(const ::std::string& value) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.HeartBeatRes.user_name)
}
inline void HeartBeatRes::set_user_name(const char* value) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.HeartBeatRes.user_name)
}
inline void HeartBeatRes::set_user_name(const char* value, size_t size) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.HeartBeatRes.user_name)
}
inline ::std::string* HeartBeatRes::mutable_user_name() {
  set_has_user_name();
  // @@protoc_insertion_point(field_mutable:YFQAppService.HeartBeatRes.user_name)
  return user_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HeartBeatRes::release_user_name() {
  clear_has_user_name();
  return user_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HeartBeatRes::set_allocated_user_name(::std::string* user_name) {
  if (user_name != NULL) {
    set_has_user_name();
  } else {
    clear_has_user_name();
  }
  user_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_name);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.HeartBeatRes.user_name)
}

// required uint32 msg_id = 2;
inline bool HeartBeatRes::has_msg_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HeartBeatRes::set_has_msg_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HeartBeatRes::clear_has_msg_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HeartBeatRes::clear_msg_id() {
  msg_id_ = 0u;
  clear_has_msg_id();
}
inline ::google::protobuf::uint32 HeartBeatRes::msg_id() const {
  // @@protoc_insertion_point(field_get:YFQAppService.HeartBeatRes.msg_id)
  return msg_id_;
}
inline void HeartBeatRes::set_msg_id(::google::protobuf::uint32 value) {
  set_has_msg_id();
  msg_id_ = value;
  // @@protoc_insertion_point(field_set:YFQAppService.HeartBeatRes.msg_id)
}

// optional string reversed = 10;
inline bool HeartBeatRes::has_reversed() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HeartBeatRes::set_has_reversed() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HeartBeatRes::clear_has_reversed() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HeartBeatRes::clear_reversed() {
  reversed_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_reversed();
}
inline const ::std::string& HeartBeatRes::reversed() const {
  // @@protoc_insertion_point(field_get:YFQAppService.HeartBeatRes.reversed)
  return reversed_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HeartBeatRes::set_reversed(const ::std::string& value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.HeartBeatRes.reversed)
}
inline void HeartBeatRes::set_reversed(const char* value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.HeartBeatRes.reversed)
}
inline void HeartBeatRes::set_reversed(const char* value, size_t size) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.HeartBeatRes.reversed)
}
inline ::std::string* HeartBeatRes::mutable_reversed() {
  set_has_reversed();
  // @@protoc_insertion_point(field_mutable:YFQAppService.HeartBeatRes.reversed)
  return reversed_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HeartBeatRes::release_reversed() {
  clear_has_reversed();
  return reversed_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HeartBeatRes::set_allocated_reversed(::std::string* reversed) {
  if (reversed != NULL) {
    set_has_reversed();
  } else {
    clear_has_reversed();
  }
  reversed_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reversed);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.HeartBeatRes.reversed)
}

// -------------------------------------------------------------------

// LogoutReq

// required string user_name = 1;
inline bool LogoutReq::has_user_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogoutReq::set_has_user_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogoutReq::clear_has_user_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogoutReq::clear_user_name() {
  user_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user_name();
}
inline const ::std::string& LogoutReq::user_name() const {
  // @@protoc_insertion_point(field_get:YFQAppService.LogoutReq.user_name)
  return user_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogoutReq::set_user_name(const ::std::string& value) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.LogoutReq.user_name)
}
inline void LogoutReq::set_user_name(const char* value) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.LogoutReq.user_name)
}
inline void LogoutReq::set_user_name(const char* value, size_t size) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.LogoutReq.user_name)
}
inline ::std::string* LogoutReq::mutable_user_name() {
  set_has_user_name();
  // @@protoc_insertion_point(field_mutable:YFQAppService.LogoutReq.user_name)
  return user_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogoutReq::release_user_name() {
  clear_has_user_name();
  return user_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogoutReq::set_allocated_user_name(::std::string* user_name) {
  if (user_name != NULL) {
    set_has_user_name();
  } else {
    clear_has_user_name();
  }
  user_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_name);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.LogoutReq.user_name)
}

// optional string reversed = 10;
inline bool LogoutReq::has_reversed() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LogoutReq::set_has_reversed() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LogoutReq::clear_has_reversed() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LogoutReq::clear_reversed() {
  reversed_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_reversed();
}
inline const ::std::string& LogoutReq::reversed() const {
  // @@protoc_insertion_point(field_get:YFQAppService.LogoutReq.reversed)
  return reversed_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogoutReq::set_reversed(const ::std::string& value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.LogoutReq.reversed)
}
inline void LogoutReq::set_reversed(const char* value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.LogoutReq.reversed)
}
inline void LogoutReq::set_reversed(const char* value, size_t size) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.LogoutReq.reversed)
}
inline ::std::string* LogoutReq::mutable_reversed() {
  set_has_reversed();
  // @@protoc_insertion_point(field_mutable:YFQAppService.LogoutReq.reversed)
  return reversed_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogoutReq::release_reversed() {
  clear_has_reversed();
  return reversed_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogoutReq::set_allocated_reversed(::std::string* reversed) {
  if (reversed != NULL) {
    set_has_reversed();
  } else {
    clear_has_reversed();
  }
  reversed_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reversed);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.LogoutReq.reversed)
}

// -------------------------------------------------------------------

// GpsReq

// required string user_name = 1;
inline bool GpsReq::has_user_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GpsReq::set_has_user_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GpsReq::clear_has_user_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GpsReq::clear_user_name() {
  user_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user_name();
}
inline const ::std::string& GpsReq::user_name() const {
  // @@protoc_insertion_point(field_get:YFQAppService.GpsReq.user_name)
  return user_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsReq::set_user_name(const ::std::string& value) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.GpsReq.user_name)
}
inline void GpsReq::set_user_name(const char* value) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.GpsReq.user_name)
}
inline void GpsReq::set_user_name(const char* value, size_t size) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.GpsReq.user_name)
}
inline ::std::string* GpsReq::mutable_user_name() {
  set_has_user_name();
  // @@protoc_insertion_point(field_mutable:YFQAppService.GpsReq.user_name)
  return user_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GpsReq::release_user_name() {
  clear_has_user_name();
  return user_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsReq::set_allocated_user_name(::std::string* user_name) {
  if (user_name != NULL) {
    set_has_user_name();
  } else {
    clear_has_user_name();
  }
  user_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_name);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.GpsReq.user_name)
}

// required double longitude = 2;
inline bool GpsReq::has_longitude() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GpsReq::set_has_longitude() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GpsReq::clear_has_longitude() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GpsReq::clear_longitude() {
  longitude_ = 0;
  clear_has_longitude();
}
inline double GpsReq::longitude() const {
  // @@protoc_insertion_point(field_get:YFQAppService.GpsReq.longitude)
  return longitude_;
}
inline void GpsReq::set_longitude(double value) {
  set_has_longitude();
  longitude_ = value;
  // @@protoc_insertion_point(field_set:YFQAppService.GpsReq.longitude)
}

// required double latitude = 3;
inline bool GpsReq::has_latitude() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GpsReq::set_has_latitude() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GpsReq::clear_has_latitude() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GpsReq::clear_latitude() {
  latitude_ = 0;
  clear_has_latitude();
}
inline double GpsReq::latitude() const {
  // @@protoc_insertion_point(field_get:YFQAppService.GpsReq.latitude)
  return latitude_;
}
inline void GpsReq::set_latitude(double value) {
  set_has_latitude();
  latitude_ = value;
  // @@protoc_insertion_point(field_set:YFQAppService.GpsReq.latitude)
}

// optional string address = 4;
inline bool GpsReq::has_address() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GpsReq::set_has_address() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GpsReq::clear_has_address() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GpsReq::clear_address() {
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_address();
}
inline const ::std::string& GpsReq::address() const {
  // @@protoc_insertion_point(field_get:YFQAppService.GpsReq.address)
  return address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsReq::set_address(const ::std::string& value) {
  set_has_address();
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.GpsReq.address)
}
inline void GpsReq::set_address(const char* value) {
  set_has_address();
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.GpsReq.address)
}
inline void GpsReq::set_address(const char* value, size_t size) {
  set_has_address();
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.GpsReq.address)
}
inline ::std::string* GpsReq::mutable_address() {
  set_has_address();
  // @@protoc_insertion_point(field_mutable:YFQAppService.GpsReq.address)
  return address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GpsReq::release_address() {
  clear_has_address();
  return address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsReq::set_allocated_address(::std::string* address) {
  if (address != NULL) {
    set_has_address();
  } else {
    clear_has_address();
  }
  address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.GpsReq.address)
}

// optional string date_time = 5;
inline bool GpsReq::has_date_time() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GpsReq::set_has_date_time() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GpsReq::clear_has_date_time() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void GpsReq::clear_date_time() {
  date_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_date_time();
}
inline const ::std::string& GpsReq::date_time() const {
  // @@protoc_insertion_point(field_get:YFQAppService.GpsReq.date_time)
  return date_time_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsReq::set_date_time(const ::std::string& value) {
  set_has_date_time();
  date_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.GpsReq.date_time)
}
inline void GpsReq::set_date_time(const char* value) {
  set_has_date_time();
  date_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.GpsReq.date_time)
}
inline void GpsReq::set_date_time(const char* value, size_t size) {
  set_has_date_time();
  date_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.GpsReq.date_time)
}
inline ::std::string* GpsReq::mutable_date_time() {
  set_has_date_time();
  // @@protoc_insertion_point(field_mutable:YFQAppService.GpsReq.date_time)
  return date_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GpsReq::release_date_time() {
  clear_has_date_time();
  return date_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsReq::set_allocated_date_time(::std::string* date_time) {
  if (date_time != NULL) {
    set_has_date_time();
  } else {
    clear_has_date_time();
  }
  date_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), date_time);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.GpsReq.date_time)
}

// optional string user_id = 6;
inline bool GpsReq::has_user_id() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void GpsReq::set_has_user_id() {
  _has_bits_[0] |= 0x00000020u;
}
inline void GpsReq::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void GpsReq::clear_user_id() {
  user_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user_id();
}
inline const ::std::string& GpsReq::user_id() const {
  // @@protoc_insertion_point(field_get:YFQAppService.GpsReq.user_id)
  return user_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsReq::set_user_id(const ::std::string& value) {
  set_has_user_id();
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.GpsReq.user_id)
}
inline void GpsReq::set_user_id(const char* value) {
  set_has_user_id();
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.GpsReq.user_id)
}
inline void GpsReq::set_user_id(const char* value, size_t size) {
  set_has_user_id();
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.GpsReq.user_id)
}
inline ::std::string* GpsReq::mutable_user_id() {
  set_has_user_id();
  // @@protoc_insertion_point(field_mutable:YFQAppService.GpsReq.user_id)
  return user_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GpsReq::release_user_id() {
  clear_has_user_id();
  return user_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsReq::set_allocated_user_id(::std::string* user_id) {
  if (user_id != NULL) {
    set_has_user_id();
  } else {
    clear_has_user_id();
  }
  user_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_id);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.GpsReq.user_id)
}

// optional string reversed = 10;
inline bool GpsReq::has_reversed() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void GpsReq::set_has_reversed() {
  _has_bits_[0] |= 0x00000040u;
}
inline void GpsReq::clear_has_reversed() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void GpsReq::clear_reversed() {
  reversed_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_reversed();
}
inline const ::std::string& GpsReq::reversed() const {
  // @@protoc_insertion_point(field_get:YFQAppService.GpsReq.reversed)
  return reversed_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsReq::set_reversed(const ::std::string& value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.GpsReq.reversed)
}
inline void GpsReq::set_reversed(const char* value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.GpsReq.reversed)
}
inline void GpsReq::set_reversed(const char* value, size_t size) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.GpsReq.reversed)
}
inline ::std::string* GpsReq::mutable_reversed() {
  set_has_reversed();
  // @@protoc_insertion_point(field_mutable:YFQAppService.GpsReq.reversed)
  return reversed_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GpsReq::release_reversed() {
  clear_has_reversed();
  return reversed_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsReq::set_allocated_reversed(::std::string* reversed) {
  if (reversed != NULL) {
    set_has_reversed();
  } else {
    clear_has_reversed();
  }
  reversed_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reversed);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.GpsReq.reversed)
}

// -------------------------------------------------------------------

// GpsRes

// required .YFQAppService.GpsResultType result_code = 1;
inline bool GpsRes::has_result_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GpsRes::set_has_result_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GpsRes::clear_has_result_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GpsRes::clear_result_code() {
  result_code_ = 0;
  clear_has_result_code();
}
inline ::YFQAppService::GpsResultType GpsRes::result_code() const {
  // @@protoc_insertion_point(field_get:YFQAppService.GpsRes.result_code)
  return static_cast< ::YFQAppService::GpsResultType >(result_code_);
}
inline void GpsRes::set_result_code(::YFQAppService::GpsResultType value) {
  assert(::YFQAppService::GpsResultType_IsValid(value));
  set_has_result_code();
  result_code_ = value;
  // @@protoc_insertion_point(field_set:YFQAppService.GpsRes.result_code)
}

// optional string result_string = 2;
inline bool GpsRes::has_result_string() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GpsRes::set_has_result_string() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GpsRes::clear_has_result_string() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GpsRes::clear_result_string() {
  result_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_result_string();
}
inline const ::std::string& GpsRes::result_string() const {
  // @@protoc_insertion_point(field_get:YFQAppService.GpsRes.result_string)
  return result_string_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsRes::set_result_string(const ::std::string& value) {
  set_has_result_string();
  result_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.GpsRes.result_string)
}
inline void GpsRes::set_result_string(const char* value) {
  set_has_result_string();
  result_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.GpsRes.result_string)
}
inline void GpsRes::set_result_string(const char* value, size_t size) {
  set_has_result_string();
  result_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.GpsRes.result_string)
}
inline ::std::string* GpsRes::mutable_result_string() {
  set_has_result_string();
  // @@protoc_insertion_point(field_mutable:YFQAppService.GpsRes.result_string)
  return result_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GpsRes::release_result_string() {
  clear_has_result_string();
  return result_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsRes::set_allocated_result_string(::std::string* result_string) {
  if (result_string != NULL) {
    set_has_result_string();
  } else {
    clear_has_result_string();
  }
  result_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), result_string);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.GpsRes.result_string)
}

// optional string reversed = 10;
inline bool GpsRes::has_reversed() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GpsRes::set_has_reversed() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GpsRes::clear_has_reversed() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GpsRes::clear_reversed() {
  reversed_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_reversed();
}
inline const ::std::string& GpsRes::reversed() const {
  // @@protoc_insertion_point(field_get:YFQAppService.GpsRes.reversed)
  return reversed_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsRes::set_reversed(const ::std::string& value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:YFQAppService.GpsRes.reversed)
}
inline void GpsRes::set_reversed(const char* value) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:YFQAppService.GpsRes.reversed)
}
inline void GpsRes::set_reversed(const char* value, size_t size) {
  set_has_reversed();
  reversed_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:YFQAppService.GpsRes.reversed)
}
inline ::std::string* GpsRes::mutable_reversed() {
  set_has_reversed();
  // @@protoc_insertion_point(field_mutable:YFQAppService.GpsRes.reversed)
  return reversed_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GpsRes::release_reversed() {
  clear_has_reversed();
  return reversed_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GpsRes::set_allocated_reversed(::std::string* reversed) {
  if (reversed != NULL) {
    set_has_reversed();
  } else {
    clear_has_reversed();
  }
  reversed_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reversed);
  // @@protoc_insertion_point(field_set_allocated:YFQAppService.GpsRes.reversed)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace YFQAppService

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::YFQAppService::MessageCmdID> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::YFQAppService::MessageCmdID>() {
  return ::YFQAppService::MessageCmdID_descriptor();
}
template <> struct is_proto_enum< ::YFQAppService::LoginResultType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::YFQAppService::LoginResultType>() {
  return ::YFQAppService::LoginResultType_descriptor();
}
template <> struct is_proto_enum< ::YFQAppService::GpsResultType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::YFQAppService::GpsResultType>() {
  return ::YFQAppService::GpsResultType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_YFQAppService_2eproto__INCLUDED
